name:                is09-ecsite-api-test
version:             0.1.0.0
github:              "githubuser/is09-ecsite-api-test"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/is09-ecsite-api-test#readme>

dependencies:
- base >= 4.7 && < 5
- http-client
- http-conduit
- bytestring
- aeson
- yaml

library:
  source-dirs: src

executables:
  is09-ecsite-api-test-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - is09-ecsite-api-test

tests:
  is09-ecsite-api-test-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - is09-ecsite-api-test
